owner: linuxtux23
repo: uptime

sites:
  - name: Primary Domain
    url: https://benedikt.tech

  - name: Secondary Domain
    url: https://benedikt-lohse.dev

  - name: Nextcloud
    url: https://cloud.benedikt.tech

  - name: Draco
    url: http://$DRACO_SERVER_IP
    expectedStatusCodes:
      - 400

  - name: Storage Box
    url: https://$MCLOUD_SERVER_IP
    expectedStatusCodes:
      - 401
      
status-website:
  cname: status.benedikt.tech
  logoUrl: https://raw.githubusercontent.com/LinuxTux23/uptime/master/assets/logo_circle_web.png
  name: Uptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
