owner: linuxtux23
repo: uptime

sites:
  - name: Primary Domain @ Draco
    url: https://benedikt.tech

  - name: Secondary Domain @ Draco
    url: https://benedikt-lohse.dev

  - name: Nextcloud @ Draco
    url: https://cloud.benedikt.tech

  - name: Cloud Server @ Draco
    url: https://$DRACO_SERVER_IP
    __dangerous__disable_verify_peer
status-website:
  cname: status.benedikt.tech
  logoUrl: https://raw.githubusercontent.com/LinuxTux23/uptime/master/assets/logo_circle_web.png
  name: Upptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
