owner: linuxtux23
repo: uptime

sites:
  - name: Primary Domain
    url: https://benedikt.tech

  - name: Secondary Domain
    url: https://benedikt-lohse.dev

  - name: Nextcloud @ VPS
    url: https://cloud.benedikt.tech

  - name: VPS
    url: https://${{ secrets.draco_server_ip }}

  - name: Storage Box
    url: https://${{ secrets.mcloud_server_ip }}
    expectedStatusCodes:
      - 401
status-website:
  cname: status.benedikt.tech
  logoUrl: https://raw.githubusercontent.com/LinuxTux23/uptime/master/assets/logo_circle_web.png
  name: Uptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
